<a href="https://colab.research.google.com/github/Arsha070302/Arsha070302/blob/main/ailab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
x=tf.constant(10)
print(x)

tf.Tensor(10, shape=(), dtype=int32)


In [2]:
x=tf.constant([1,2,3])
print(x)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [3]:
x=tf.constant([(1,2),(3,4),(5,6)])
print(x)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [4]:
x=tf.ones(3,3)
print(x)

y=tf.zeros(3,3)
print(y)

# identity metrix
z=tf.eye(3,3)
print(z)

a=tf.eye(3)
print(a)

tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([0 0 0], shape=(3,), dtype=int32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [5]:
x=tf.range(10)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [6]:
x=tf.cast(x,dtype=tf.float32)
print(x)

tf.Tensor([0. 1. 2. 3. 4. 5. 6. 7. 8. 9.], shape=(10,), dtype=float32)


In [7]:
x=tf.constant([1,2,3])
y=tf.constant([4,5,6])
z=x+y
print(z)

# or

z=tf.add(x,y)
print(z)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [8]:
x=tf.constant([1,2,3])
y=tf.constant([4,5,6])
z=x-y
print(z)

# or

z=tf.subtract(x,y)
print(z)

tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)


In [9]:
x=tf.constant([1,2,3])
y=tf.constant([4,5,6])
z=x*y
print(z)

# or

z=tf.multiply(x,y)
print(z)

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [10]:
x=tf.constant([1,2,3])
y=tf.constant([4,5,6])
z=x/y
print(z)

# or

z=tf.divide(x,y)
print(z)

tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)
tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [11]:
x=tf.constant([1,2,3])
y=tf.constant([4,5,6])
z=tf.tensordot(x,y,axes=1)
print(z)

tf.Tensor(32, shape=(), dtype=int32)


In [12]:
x=tf.constant([1,2,3])
y=x**3
print(y)

tf.Tensor([ 1  8 27], shape=(3,), dtype=int32)


In [13]:
x = tf.constant([[1,2,3]])
y = tf.constant([[4,5,6], [7,8,9], [10,11,12]])
z = tf.matmul(x, y)
print(z)

tf.Tensor([[48 54 60]], shape=(1, 3), dtype=int32)


In [14]:
newlist=[3,[5,4,0],"hello",[7,4,1]]
print(newlist)
print("First element of the new list is :",newlist[0])
print("Second element of the new list is :",newlist[1])
print("Third element of the new list  is :",newlist[2])
print("Fourth element of the new list is :",newlist[3])

[3, [5, 4, 0], 'hello', [7, 4, 1]]
First element of the new list is : 3
Second element of the new list is : [5, 4, 0]
Third element of the new list  is : hello
Fourth element of the new list is : [7, 4, 1]


In [15]:
print("First three elements of newlist",newlist[9:3])
print("Last three elements of newlist",newlist[0:4:2])

First three elements of newlist []
Last three elements of newlist [3, 'hello']


In [16]:
newlist.append("hai")
print("The appended new list is: ",newlist)

newlist.remove("hai")
print("The removed new list is: ",newlist)

The appended new list is:  [3, [5, 4, 0], 'hello', [7, 4, 1], 'hai']
The removed new list is:  [3, [5, 4, 0], 'hello', [7, 4, 1]]


In [17]:
import numpy as np

a=np.array([1,2,3])
print("The array is",a,"and the data type is",type(a))

The array is [1 2 3] and the data type is <class 'numpy.ndarray'>


In [18]:
list1=[1,2,3]
float_data=np.array(list1,dtype=float)
print("float_data is",float_data,"and data type is ",type(float_data))

float_data is [1. 2. 3.] and data type is  <class 'numpy.ndarray'>


In [19]:
list2=[11,12,13]
arr1=np.array(list1)
arr2=np.array(list2)
print("arr1 is",arr1,"and arr2 is",arr2)
sum=arr1+arr2
print("The sum of arr1 and arr2 is",sum)

arr1 is [1 2 3] and arr2 is [11 12 13]
The sum of arr1 and arr2 is [12 14 16]


In [20]:
data=[[1,2,3,4],[5,6,7,8]]
arr3=np.array(data)
print("The array is",arr3)
print("The dimension of the array is",arr3.ndim)
print("The data type of the array is",arr3.dtype)
print("The shape of the array is",arr3.shape)

The array is [[1 2 3 4]
 [5 6 7 8]]
The dimension of the array is 2
The data type of the array is int64
The shape of the array is (2, 4)


In [21]:
arr4=np.array(data,dtype=float)
print("The array is",arr4)
print("The dimension of the array is",arr4.ndim)
print("The data type of the array is",arr4.dtype)
print("The shape of the array is",arr4.shape)

The array is [[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
The dimension of the array is 2
The data type of the array is float64
The shape of the array is (2, 4)


In [22]:
arr5=np.arange(7)
print(arr5)

arr6=np.arange(4,20,2)
print(arr6)

[0 1 2 3 4 5 6]
[ 4  6  8 10 12 14 16 18]


In [23]:
a=np.arange(10).reshape(5,2)
print("Numpy array is : ",a)
print("Size of the array is :",np.size(a))
print("Shape of the array is :",np.shape(a))
print("Reshape of the array is :",np.reshape(a,(2,5)))
print(np.ravel(a))
print(np.transpose(a))
print(np.where(a>5))
print(a[np.where(a>5)])

Numpy array is :  [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
Size of the array is : 10
Shape of the array is : (5, 2)
Reshape of the array is : [[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
[[0 2 4 6 8]
 [1 3 5 7 9]]
(array([3, 3, 4, 4]), array([0, 1, 0, 1]))
[6 7 8 9]


In [24]:
import numpy as np
arr9=np.linspace(1,30,5)
arr9

array([ 1.  ,  8.25, 15.5 , 22.75, 30.  ])

In [25]:
arr10=np.arange(10,81,2).reshape(6,6)
arr10

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78, 80]])

In [27]:
arr10[:,[0,2]]

array([[10, 14],
       [22, 26],
       [34, 38],
       [46, 50],
       [58, 62],
       [70, 74]])

In [28]:
arr10[:2,:]

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32]])

In [29]:
arr11=np.array([38,40,42,50])
arr11

array([38, 40, 42, 50])

In [30]:
np.sum(arr11)

170

In [31]:
np.mean(arr11)

42.5

In [32]:
np.median(arr11)

41.0

In [33]:
arr11=arr11.reshape(2,2)
arr11

array([[38, 40],
       [42, 50]])

In [34]:
arr11.sum(axis=1)

array([78, 92])

In [35]:
arr11.sum(axis=0)

array([80, 90])

In [36]:
arr10+5

array([[15, 17, 19, 21, 23, 25],
       [27, 29, 31, 33, 35, 37],
       [39, 41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59, 61],
       [63, 65, 67, 69, 71, 73],
       [75, 77, 79, 81, 83, 85]])

In [37]:
arr10-5

array([[ 5,  7,  9, 11, 13, 15],
       [17, 19, 21, 23, 25, 27],
       [29, 31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49, 51],
       [53, 55, 57, 59, 61, 63],
       [65, 67, 69, 71, 73, 75]])

In [39]:
arr10*3

array([[ 30,  36,  42,  48,  54,  60],
       [ 66,  72,  78,  84,  90,  96],
       [102, 108, 114, 120, 126, 132],
       [138, 144, 150, 156, 162, 168],
       [174, 180, 186, 192, 198, 204],
       [210, 216, 222, 228, 234, 240]])

In [40]:
arr10/2

array([[ 5.,  6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15., 16.],
       [17., 18., 19., 20., 21., 22.],
       [23., 24., 25., 26., 27., 28.],
       [29., 30., 31., 32., 33., 34.],
       [35., 36., 37., 38., 39., 40.]])

In [41]:
arr10[5]=-9
arr10

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [-9, -9, -9, -9, -9, -9]])

In [42]:
arr10=np.abs(arr10)
arr10

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [ 9,  9,  9,  9,  9,  9]])

In [43]:
np.sqrt(arr10)

array([[3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069,
        4.47213595],
       [4.69041576, 4.89897949, 5.09901951, 5.29150262, 5.47722558,
        5.65685425],
       [5.83095189, 6.        , 6.164414  , 6.32455532, 6.4807407 ,
        6.63324958],
       [6.78232998, 6.92820323, 7.07106781, 7.21110255, 7.34846923,
        7.48331477],
       [7.61577311, 7.74596669, 7.87400787, 8.        , 8.1240384 ,
        8.24621125],
       [3.        , 3.        , 3.        , 3.        , 3.        ,
        3.        ]])

In [44]:
arr10.T

array([[10, 22, 34, 46, 58,  9],
       [12, 24, 36, 48, 60,  9],
       [14, 26, 38, 50, 62,  9],
       [16, 28, 40, 52, 64,  9],
       [18, 30, 42, 54, 66,  9],
       [20, 32, 44, 56, 68,  9]])

In [45]:
np.random.rand(2,3)

array([[0.89857579, 0.01945238, 0.99513934],
       [0.69627625, 0.6546256 , 0.21450679]])